name: Build test env

on:
  push:
    brabches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Instal dependencies
        run: |
          npm i -D

      - name: Build app
        run: |
          npm run build:prod

      - name: Init ssh
        run: |
          mkdir -p ~/.ssh
          echo $SSH_DEPLOY_KEY &gt;&gt; ~/.ssh/id_rsa
          scp ./build/ $SERVER:${APP_PATH}/test/
        env:
          SSH_DEPLOY_KEY : ${{secrets.SSH_DEPLOY_KEY}}
          SERVER: ${{secrets.SERVER}}
          APP_PATH: ${{secrets.APP_PATH}}
