name: Build releasse env

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Instal dependencies
        run: |
          npm i -D

      - name: Build app
        run: |
          npm run build:prod
          npm run release

      - name: CompressFiles
        uses: stefh/ghaction-CompressFiles@v2
        with:
          path: ./dist/
          extensions: '.html,.css,.js,.png,.jpg,.jpeg,.svg,.webp'
          tools: 'brotli,gzip'

      - name: Publish
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: ./dist
          target: ${{ secrets.APP_PATH }}
